const ADDRESS_1 = process.env.ETH_ADDRESS_1;
const ADDRESS_2 = process.env.ETH_ADDRESS_2;

const INFURA_PROJECT_ID = process.env.INFURA_PROJECT_ID;
const INFURA_MAINNET_ENDPOINT = process.env.INFURA_MAINNET_ENDPOINT;
const INFURA_ROPSTEN_ENDPOINT = process.env.INFURA_ROPSTEN_ENDPOINT;

export {
  ADDRESS_1,
  ADDRESS_2,
  INFURA_PROJECT_ID,
  INFURA_MAINNET_ENDPOINT,
  INFURA_ROPSTEN_ENDPOINT,
};
